## Day objectives
#### functional programming
#### list comprehension
#### iterators and generators
#### map
#### filter 
#### lambda



In [6]:
## list comprehension 
# list comprehension is very easy way to create list
## compared with for loop
# programing using list comprenhension
n=20
li=[]
for i in range(1,n+1):## using for loop
    li.append(i)
print(li)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [7]:
## using list comprehension
li=[i for i in range (1,19)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [8]:
#cubes
li=[i**3 for i in li]
li

[1,
 8,
 27,
 64,
 125,
 216,
 343,
 512,
 729,
 1000,
 1331,
 1728,
 2197,
 2744,
 3375,
 4096,
 4913,
 5832]

In [11]:
#squaring
k=[10,20,5,2]
k=[i**2 for i in k]
k

[100, 400, 25, 4]

In [15]:
## leap year using list comprenhension
st=1970
et=2020
leapyear=[i for i in range(st,et+1)
    if(i%100==0 and i%4==0)]
leapyear    

[2000]

In [13]:
st=1940
et=2010
leapyear=[i for i in range(st,et+1)
    if(i%4==0)]
leapyear    

[1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008]

In [20]:
# cumalitive sum
def cumalativesum(n):
    sum=0
    li=[]
    for i in range(1,n+1):
        sum=sum+i
        print(sum)
        li.append(sum)
        print(li)
cumalativesum(4)

1
[1]
3
[1, 3]
6
[1, 3, 6]
10
[1, 3, 6, 10]


In [28]:
n=6
cumulativesum=[sum(range(1,i+1)) for i in range(1,n+1)]
cumulativesum

[1, 3, 6, 10, 15, 21]

## iterators


In [29]:
## iterators is an object that contain numbers of elements
# 2 methods
## iter()
## next()
#all ds are all iterable objects

In [ ]:
number=int(input("enter a number"))
n=[sum(range(1,i+1)) for i in range(1,number+1)]
print(n)
number=int(input("enter a number"))
a=1
a=a*i
n=[a*i for i in range(1,number+1)]
print(n)

enter a number45
[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351, 378, 406, 435, 465, 496, 528, 561, 595, 630, 666, 703, 741, 780, 820, 861, 903, 946, 990, 1035]


In [3]:
n="python_program"
n=iter("python_program")
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))

p
y
t
h
o
n
_
p
r
o
g
r
a
m


In [2]:
btech_courses=["ECE","IT","CSE","CIVIL","MECH","EEE"]
lamb=iter(btech_courses)
print(next(lamb))
print(next(lamb))
print(next(lamb))
print(next(lamb))
print(next(lamb))
print(next(lamb))

ECE
IT
CSE
CIVIL
MECH
EEE


In [4]:
# generators
## generators is a function . we can create iterators 
# in other words generator is a function which return
# it uses "yeild" instead of return

In [5]:
def generatorfunction():
    yield 1
    yield 2
    yield 3
generatorfunction()
for value in generatorfunction():
    print(value)
    

1
2
3


In [6]:
def generator_function():
    yield "vamshi"
    yield "is a"
    yield "good boy"
print(generator_function())
for i in generator_function():
    print(i)

<generator object generator_function at 0x00000227EA910D00>
vamshi
is a
good boy


In [9]:
## squaring of a numbers  up to given range
def gen():
    n=2
    while True:
        n**=2
        yield n
a=gen()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296


## maps

In [10]:
## it produces a list of results that it apply given function to each item of a given iterable (list,tuple,sets etc...)

In [11]:
def addition(n):
    return n+n
result = list(map(addition,range(1,5)))
print(result)

[2, 4, 6, 8]


In [13]:
def multiplication(k):
    return k*2
result = list(map(multiplication,range(1,10)))
print(result)


[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [14]:
## print squares of numbers in  agiven range between 1 to 5
def squareofnumb(n):
    return n*n
result=set(map(squareofnumb,range(1,5)))
print(result)

{16, 1, 4, 9}


In [15]:
def squareofnumb(n):
    return n*n
result=tuple(map(squareofnumb,range(1,5)))
print(result)

(1, 4, 9, 16)


## FILTERS IN PYTHON 

In [17]:
#filters function in python is used to check whether given element is boolean or not . this method filters the given iterable 
##tests each element is true or false and returns the element which is true
##Syntax:f:x->{T,F}


In [26]:
li=[1,2,'a','b','c',3]
def isdigit(c):
    c=str(c)
    if c.isdigit():
        return True
    return False
isdigit('a')
list(filter(isdigit, li))

[1, 2, 3]

## numpy


 - numpy is a python library and a fundamental pak=ckage for scientific computing in python
- it is used to create multidimensional arrays for fast operations
- use the following import conversion to access numpy library
- import numpy as np
- numpy have a fixed size of arrays used to  store collection of elements, unlike python lists

In [4]:
# creating 1D array using numpy
import  numpy as np
array_1d=np.array([2,4,5,6,7,9])
print(array_1d)

[2 4 5 6 7 9]


In [12]:
# creating 2D array
import  numpy as np
array_2d=np.array([[2,3,4],[6,7,8]])
print(array_2d)

[[2 3 4]
 [6 7 8]]


In [13]:
# creating 3D array
import  numpy as np
array_3d=np.array([[2,3,4],[6,7,8],[9,10,11]])
print(array_3d)

[[ 2  3  4]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
# program to print the given list into an array
import numpy as np
li = [1,2,3,'z']
a=np.array(li)
print(a)

['1' '2' '3' 'z']


- if the size of the array is large to type , we can simply use array range called "arrange"

In [18]:
# example
# To print 1D array between 1 to 15
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [38]:
import numpy as np
a2=np.arange(1000).reshape(100,100)
a2

ValueError: cannot reshape array of size 1000 into shape (100,100)

## PANDAS

- Pandas basically use for data analysis.It is build on top of Numpy only
- We will mostly be using this pandas package a lot
- In fact, if you are going to use it heavily for any data manipulation, any sort of data analysis and any
  sort of data_visualization, and sort of MACHINE LEARNING MODEL BUILDING
  ##### DataVisualization.


###  create panda series

In [43]:
import pandas as pd 


AttributeError: module 'pandas' has no attribute 'series'

In [45]:
a=pd.Series([1,2,3,4,5])    #pandas also homogenous array

In [46]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [47]:
type(a)

pandas.core.series.Series

In [48]:
a[2]

3

In [4]:
import pandas as pd
a=pd.data_range(start='08-01-2019', end='20-09-2022')
a

AttributeError: module 'pandas' has no attribute 'data_range'

## PANDAS DATA FRAME

- Data frame is just like a table . which is going to contain rows and columns
- row can have a index
- column can have a meaning full names

In [5]:
import numpy as np

In [11]:
temp=np.random.randint(low=20,high=100,size=[20])
name=np.random.choice(['ravi','kishore','anil','kumar'],20)
av=np.random.choice([10,12,13,34,56],20)

In [12]:
a=list(zip(temp,name,av))

In [13]:
df=pd.DataFrame(data=a,columns=['temp','name','av'])
df

temp     name  av
0     46    kumar  10
1     44    kumar  34
2     48    kumar  10
3     43     anil  12
4     82  kishore  13
5     40    kumar  34
6     50  kishore  34
7     88     anil  12
8     72    kumar  10
9     83    kumar  34
10    41     anil  56
11    31     anil  13
12    97    kumar  56
13    85     anil  12
14    31     ravi  56
15    24    kumar  13
16    85     anil  10
17    49  kishore  12
18    65     anil  56
19    44     anil  10

In [2]:
import numpy as np
temp=np.random.randint(low=20,high=100,size=[20])
temp

array([99, 36, 76, 24, 77, 24, 53, 64, 39, 92, 20, 59, 33, 66, 82, 27, 28,
       98, 27, 54])

In [6]:
import numpy as np
name=np.random.choice(['ravi','kishore','anil'],30)
name

array(['anil', 'kishore', 'ravi', 'ravi', 'kishore', 'kishore', 'anil',
       'kishore', 'ravi', 'kishore', 'kishore', 'kishore', 'kishore',
       'kishore', 'ravi', 'anil', 'ravi', 'ravi', 'kishore', 'kishore',
       'kishore', 'kishore', 'anil', 'kishore', 'ravi', 'ravi', 'kishore',
       'kishore', 'anil', 'ravi'], dtype='<U7')

In [ ]:
df.head=pd.DataFrames